#!/usr/bin/env bash

function git_current_branch() {
  git symbolic-ref --short HEAD
}

function git_current_commit_hash() {
  git rev-parse --short HEAD
}

function build_environment() {
  if [ -z ${ENVIRONMENT+x} ]; then
      echo "localenv"
    else
      echo "$ENVIRONMENT"
    fi
}

function go_build_info_ldflags() {
  echo "-X $1/build.Branch=$(git_current_branch) -X $1/build.Commit=$(git_current_commit_hash) -X $1/build.Host=$(hostname) -X $1/build.Environment=$(build_environment)"
}

##
function go_build_with_version_info() {
  out=$1
  go_module_path=$2
  package=$3
  go build -o "$out" -ldflags "$(go_build_info_ldflags "$go_module_path")" "$package"
}

function makeHelp() {
  grep '^.PHONY: .* #' makefile | sed 's/\.PHONY: \(.*\) # \(.*\)/\1 	\2/' | expand -t20
}