### GET /foodlisting (list all foods)
GET {{base_url}}/foodlisting?q=appl

###

### POST request to /foodlisting (create a food)
POST {{base_url}}/foodlisting
Content-Type: application/json

{
  "name": "apple",
  "servings": {
    "100g": {
      "carbs": 1,
      "fats": 2,
      "proteins": 3
    }
  }
}

###