### GET /foodlisting (list all foods)
GET {{base_url}}/foodlisting?q=bacon

###

### POST request to /foodlisting (create a food)
POST {{base_url}}/foodlisting
Content-Type: application/json

{
  "name": "bacon",
  "servings": {
    "size": "100g",
    "macros": {
      "carbs": "1",
      "fats": "1",
      "proteins": "1"
    }
  }
}

###